export default {
    // cart
    CART_COUNT_INCREMENT:'CART_COUNT_INCREMENT',
    CART_COUNT_DECREMENT: 'CART_COUNT_DECREMENT',
    // blog
    START_FETCH_BLOGS: 'START_FETCH_BLOGS',
    FETCH_BLOGS_SUCCESS: 'FETCH_BLOGS_SUCCESS',
    FETCH_BLOGS_FAILED: 'FETCH_BLOGS_FAILED',
}